services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: head-office-api
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - xray
      - postgres

  xray:
    image: amazon/aws-xray-daemon
    container_name: xray
    restart: always
    ports:
      - "2000:2000/udp"
    env_file:
      - .env
    command: -o

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: